hmcts/div-case-data-formatter

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/FeeItem.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/FeeResponse.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/FeeValue.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/OrderSummary.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/AddDocumentsSolicitorITest.java, src/test/resources/fixtures/model/ccd/solicitorCaseDocumentsInput.json, src/test/resources/fixtures/model/ccd/solicitorCaseDocumentsOutput.json
Missing solicitor fields meant that when a caseworker issued a Solicitor case, the Solicitor details were lost, as on issue the formatter is called. This adds in the missing fields and since they are JSON ignored, it shouldn't impact anything else. Also null fields are ignored when returned to the calling service.
=> [PREVIEW] Add in missing Solicitor fields and required data type

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/AddressesCaseToCCDMapperUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/empty-respondent-home-addresscase.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/respondent-home-addresses-empty.json
DIV-3335 Fix Nullpointer error when  respondentHomeAddress has only AddressType attribute filled. 
* Hardware:
* JDK:
=> [PREVIEW] DIV-3335 Fix Nullpointer error on empty respondentHomeAddress

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/AdulteryStrategy.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/DesertionStrategy.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/SeparationFiveYearsStrategy.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/SeparationTwoYearsStrategy.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/util/DateUtil.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/AdulteryStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/DesertionStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/SeparationFiveYearsStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/reasonfordivorce/SeparationTwoYearsStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/util/DateUtilUTest.java
Due to the new draft retrieval format of converting to CCD first then DivorceSession and then returning to frontend, its possible to attempt mapping of partial data to CCD format.
This can cause NullPointerExceptions in certain scenarios, mainly around the derived field mapping.
As derived fields are being removed, this fix will just convert to Optionals and set default values if they don't exist.
We probably should raise a story removing non address derived field mappings soon as I don't believe they are in use or required now,
=> Allow derived fields mapping to be nullable

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/AddressesNullFieldsCaseToCCDMapperUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/nulladdressfields.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/null-address-fields.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/nullfields.json
SolicitorName and SolicitorFirm were not being mapped.
Also Address fields with null values could cause an NPE when mapping the address to derived address format.
This also checks the null value of that particular field.
=> Added in missing solicitor fields and fix null address scenarios

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/payment/PaymentCollection.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategyUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json
Due to CCD CRUD update on Collection Elements, our Payment code which removes existing references broke. We don't want to put Delete permissions on Payments, so this PR changes so that it only updates existing payments.
Assuming we don't get duplicate PaymentReference payments now. Even if there is, they will all be updated to the same values which should always be the latest Gov UK status.
=> Change ExistingPayment update logic to replace existing payments only

build.gradle
This is to fix the sonar failing issue.
Sonar is reporting incorrectly that there is duplicate code block between CCDCaseToDivorceMapper and DivorceCaseToCCDMapper, when the code block in question is a reverse mapping.
This change just excludes the two classes from the duplicate code check.
=> Exclude code duplication check for the Mapper classes

src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToCCDFormatErrorHandlingTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToCCDFormatTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/additionalpayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/hownamechanged.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdiction612.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdictionall.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentcase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentidonly.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonadultery.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasondesertion.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonunreasonablebehaviour.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/samesex.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/payment/Payment.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImpl.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/TransformToCCDFormatITest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImplUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/NoExistingPaymentReferenceStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/NoExistingPaymentStrategyUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/PaymentContextUTest.java
For [DIV-3645](https://tools.hmcts.net/jira/browse/DIV-3645)
Payment callback returns a response like:
{"_links":{"self":{"href":"http://payment-api-aat.service.core-compute-aat.internal/card-payments/RC-1549-3140-5487-8260","method":"GET","methAod":"GET"}},"amount":550,"ccd_case_number":"1549314051019462","channel":"online","currency":"GBP","description":"Filing an application for a divorce, nullity or civil partnership dissolution – fees order 1.2.","external_provider":"gov pay","external_reference":"555ufapesk8daponmgffe4b3vv","fees":[{"calculated_amount":550,"code":"FEE0002","version":"4","volume":1}],"method":"card","payment_group_reference":"2019-15493140548","reference":"RC-1549-3140-5487-8260","service_name":"Divorce","site_id":"CTSC","status":"Success"}
Which is missing the …
=> Replace exisitngPayment properties that are not null only

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/TranslateAnswer.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/YesNoNeverAnswer.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToAosCaseMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/MappingCommons.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/StringCollectionCCDFormatMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/StringCollectionDivorceFormatMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/TranslateAnswerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/YesNoNeverAnswerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/AmendPetitionSubmissionUTest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/addressabroadcase.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses-abroad.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/amend-petition-ccd-submitted.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/amend-petition-session-submit.json
Ensure CCD Collections type is mapped correctly from divorce session, for PreviousReasonsForDivorceField. 
In fixing DIV-4280 the mapper allows for "NEVER" as a value alongside "YES" and "NO"
Fixes # DIV-4275 & DIV-4280
Unit, ITest
=> DIV-4275 Added mapping for CCD collection format in previous reasons for divorce

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json
[DIV-4267](https://tools.hmcts.net/jira/browse/DIV-4267);
Adds respDefendsDivorce field to CCD and DivorceSession models. Since the field key names are the same, the AOSMapper automatically maps it.
Unit tests and manual
=> DIV-4267 Add respDefendsDivorce

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json
Reverts hmcts/div-case-data-formatter#95
RespDefendsDivorce is an old field. This mapping is not required, as RespWillDefendDivorce, the replacing field is already mapped.
The fix this PR was meant to apply will be done on the frontend instead:
https://github.com/hmcts/div-respondent-frontend/pull/231
=> Revert "DIV-4267 Add respDefendsDivorce"

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/DivorceCaseToDnCaseMapperUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/dn-behaviour.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/dn-desertion.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/dn-separation.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn-behaviour.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn-desertion.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn-separation.json
[DIV-4216](https://tools.hmcts.net/jira/browse/DIV-4216)
Change the mapping for approximateDatesOfLivingTogetherField based on the reason for divorce. Since we do not have the actual reason for divorce field available at this point, used the other relevant fields to determine which field to map the above to.
=> Set TimeLivedTogetherDetails based on reason for Divorce

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/d8-document.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CaseLink.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/amend-petition-case.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/amend-petition-divorce.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/amend-petition-ccd-submitted.json
DIV-4329 Map previous link from TextField to CCD CaseTypeLink type.
Changed the mapping in the CFS so that it:
- can consume CCD previousCaseId as text from Divorce Session Data and transform this into a new CaseLink type within the CCD data. 
- Transform data in this new CaseLink type from CCD data to a text field in the Divorce Session data. 
See below for more information on this new CaseLink type created by CCD
https://github.com/hmcts/ccd-data-store-api/blob/master/docs/api/case-data.md#caselink
=> DIV-4329: Map previous link from textField to new CCD CaseLink type object

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/config/HttpConnectionConfiguration.java, src/test/resources/logback-test.xml
It's causing more than 1 million log messages in production
https://github.com/hmcts/java-logging/blob/master/java-logging-httpcomponents/src/main/java/uk/gov/hmcts/reform/logging/httpcomponents/OutboundRequestLoggingInterceptor.java#L41
Also reduced test loggin to WARN
Before:
After:
Fixes #DIV-3956
=> DIV-3956 - reduced logging noise

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/addresses.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/addresses.json
Note: Only merge after fields have been verified to be merged in CCD.
- Verified in Prod. Merge this in and then merge
https://github.com/hmcts/div-petitioner-frontend/pull/523
Adds the required Respondent Solicitor Email and Phone fields to be mapped.
[DIV-4726](https://tools.hmcts.net/jira/browse/DIV-4726)
Unit tests ran.
=> Add Respondent Solicitor Email and Phone contact fields

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DocumentCollectionDivorceFormatMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DocumentCollectionDivorceFormatMapperUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DocumentsMappingUTest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/document-dates-empty.json
We have a bug in Prod where we see Parse errors when trying to parse an empty string.
See ticket for more details. 
[Prevent Parse errors when document date is empty string](https://tools.hmcts.net/jira/browse/DIV-4929)
=> DIV-4929 Apply fix for document mapping and checking if date is empty string

charts/div-cfs/values.aat.template.yaml, charts/div-cfs/values.preview.template.yaml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/preview.tfvars, infrastructure/variables.tf
To prevent hammering AAT, as every `/health` call checks _every_ dependent service, generating sometimes ~30 subsequent calls (e.g COS)
Tested locally via
`MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE=60000 ./gradlew clean bootrun`
=> Override Spring's management endpoint cache to 30 seconds in AAT/Preview

build.gradle, ruleset.xml
Previously the Gradle build would be polluted with hundreds of lines of warnings about migration of rulesets to new files. This change migrates to the new rulesets and also carries over the rule exclusions that we have. This makes the build output far more readable.
Fixes # 
[DIV-4835 Fix PMD/checkstyle warnings](https://tools.hmcts.net/jira/browse/DIV-4835)
Reduce log pollution
Run command 
```bash
./gradlew clean build
```
from project directory and check build output for occurrence of ruleset migration messages.
=> DIV-4835 Fix PMD/checkstyle warnings

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/HearingDateTime.java
When the generate-document endpoint on COS was triggered, it calls CFS to add the newly generated document to the existing, it maps the input data to the CoreCaseData model on CFS. This model is set to ignoreUnknownProperties so it drops fields that aren't defined in the model, in this case all the recently added fields for Bulk Case Listing.
This PR simply adds in the missing fields so they aren't lost at the mapping stage, whilst we probably discuss a more ideal solution.
Model change so no internal automated test. Manual test will prove this, and an upcoming COS integration test.
* Hardware:
* JDK:
=> Added CCD fields that are being removed on Add Document Mapper

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseDataJsonTest.java, src/test/resources/fixtures/model/ccd/CoreCaseData.json, src/test/resources/fixtures/model/ccd/InputCoreCaseDataMap.json
This fixes the wrong model format for bulkListingCaseId.
Unit test for earlier merge of PR #141 
This ensures that if a model property is removed from CoreCaseData, it'll fail the unit test if no changes are made to the JSON. This is because CFS will primarily be taking in JSON requests from Case Orchestration Service that have been built as a Map.
=> Added unit test for Json parsing CoreCaseData from Map

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/test/resources/fixtures/model/ccd/CoreCaseData.json, src/test/resources/fixtures/model/ccd/InputCoreCaseDataMap.json
Adds DAEligibleFromDate to CoreCaseData model so the field is not stripped out in CCD Callback Requests.
* Hardware:
* JDK:
=> Map DAEligibleFromDate

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DecreeNisiOutcomeMapperUTest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/decree-nisi-outcome.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/decree-nisi-outcome.json
[DIV-5001](https://tools.hmcts.net/jira/browse/DIV-5001)
Frontend wasn't receiving the WhoPaysCosts and TypeCostsDecision fields since the mapping was missing from CFS. This PR adds to the model and mapper.
Automated testing
- [xI have added tests that prove my fix is effective or that my feature works
=> Map Decree Nisi Outcome fields to Divorce Session

build.gradle, checkstyle.xml, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/CaseFormatterServiceApplicationTests.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/AddDocumentsITest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/WebServiceHealthCheckUTest.java
- OWASP upgraded to v5, fixed arising vulnerabilities in swagger and elasticsearch
- Checkstyle upgraded to 8.21 with an accompanying modification to the `checkstyle.xml` file
Fixes # [DIV-5057](https://tools.hmcts.net/jira/browse/DIV-5057)
=> DIV-5057: OWASP upgrade

src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToDecreeAbsoluteCaseDataTest.java, src/integrationTest/resources/application.properties, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/da.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/da.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/CaseFormatterController.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DaCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDaCaseMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/CaseFormatterService.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/CaseFormatterControllerUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/GetDecreeAbsoluteCaseDataITest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/DecreeAbsoluteToCCDMapperUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImplUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/da.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/da.json
[DIV-5111](https://tools.hmcts.net/jira/browse/DIV-5111)
Requested to store ApplyForDecreeAbsolute field into CCD. This config change will be done by Gavin.
* Hardware:
* JDK:
=> Map DivorceSession Decree Absolute to CCD Fields

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java
When formatting DN to CCD, when DN is extending DA, it is setting those DA fields to null and passing it to CCD.
However the DA fields are not yet in Production config, so an No Field Found error is thrown.
The DA update is standalone right now, and does not require mapping from CCD to Divorce, so there isn't a requirement for it to be part of the main CoreCaseData model, so the quickest fix to resolve Production issues is to remove the inheritance.
* Hardware:
* JDK:
=> Don't extend DN with DA

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/CaseFormatterController.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnRefusalCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnClarificationMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/CaseFormatterService.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/service/impl/CaseFormatterServiceImpl.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DecreeNisiClarificationMapperUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/DivorceCaseToDnClarificationMapperUTest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/dn-clarification.json, src/test/resources/fixtures/ccdtodivorcemapping/ccd/dn-refusal.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/dn-refusal.json
https://tools.hmcts.net/jira/browse/DIV-5784
Allows Legal Advisor populated DN Rejection fields to be passed back to frontend.
* Hardware:
* JDK:
=> Add DN Rejection Fields for CCD to Divorce Mapping

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn.json
Adding Service Application fields to divorce and AOS session so it can be used by frontends
Fixes https://tools.hmcts.net/jira/browse/DIV-6230
* Hardware:
* JDK:
=> DIV-6230: Adding Service Application fields to divorce and AOS session so it can be used by frontends

build.gradle
Bump common lib from 1.2.3 to 1.2.4
https://tools.hmcts.net/jira/browse/DIV-6645
Add `servedByAlternativeMethod`
| Repo  | Link | Status | Issue
|-----|------|--------|-------|
| Comlib |https://github.com/hmcts/div-common-lib/pull/44      |    🟣Merged       |  |
| COS |https://github.com/hmcts/div-case-orchestration-service/pull/1164      |  🔴 Failed      |  CVE-2020-25638, CVE-2020-13956  |
| CDF |https://github.com/hmcts/div-case-data-formatter/pull/234      | 🔴 Failed       | CVE-2020-13956  |
| CMS  | https://github.com/hmcts/div-case-maintenance-service/pull/379     |   🔴 Failed     |  |
```
One or more dependencies were identified with known vulnerabilities in div-case-formatter-service:
httpclient-4.5.10.jar (pkg:maven/org.apache.httpcomponents/httpclient@4.5.10, …
```
=> DIV-6645-Bump common lib from 1.2.3 to 1.2.4
