src/integrationTest/java/uk/gov/hmcts/reform/divorce/AddDocumentsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToCCDFormatTest.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java
Added respondentLetterHolderId to caseData
* Hardware:
* JDK:
=> [PREVIEW] Div 3132 add respondent letter holder

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/divorce/AddDocumentsTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToCCDFormatTest.java, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/additionalpayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/hownamechanged.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdiction612.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdictionall.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentcase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentidonly.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonadultery.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasondesertion.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonunreasonablebehaviour.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/samesex.json, src/integrationTest/resources/fixtures/model/ccd/addDocumentsOutput.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java
Changed the name to AosLetterHolderId
* Hardware:
* JDK:
=> [PREVIEW] aos letter holder id changes

src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/resources/application.yml, src/test/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses-abroad.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses-null.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/payment.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json
Add court to session
* Hardware:
* JDK:
=> [PREVIEW] add courtDetails to divorce session

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/functionaltest/TransformToCCDFormatITest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json
Adding Family Man Reference to Case Data
* Hardware:
* JDK:
=> [PREVIEW] add Family Man Ref to the Divorce Session

Dockerfile, Jenkinsfile_CNP, src/kubernetes/config.aat.yaml, src/kubernetes/deployment.template.yaml
=> enable aks on build pipeline

src/kubernetes/deployment.template.yaml
=> use host routing for AKS ingress

src/integrationTest/java/uk/gov/hmcts/reform/divorce/CCDToDivorceFormatTest.java, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/additionalpayment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/hownamechanged.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/jurisdiction612.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/jurisdictionall.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/paymentcase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasonadultery.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasondesertion.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasonunreasonablebehaviour.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/samesex.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java
The new field will be displayed to show the petition issue date
Fixes #3236
=> DIV-3321 - added issueDate fields to DivorceSession

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
Tag deploys only to preview
* Hardware:
* JDK:
=> [PREVIEW] use shared ASP and preview deployment option

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java
=> [PREVIEW] fix null pointer in condition

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/reason-separation.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/reasonseparation.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/reason-separation.json
add respondent consent given to case
* Hardware:
* JDK:
=> add respondent consent given to case

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java
=> changes to mapping adultery date

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java
Accept map format for case data
* Hardware:
* JDK:
=> courts format to Map<String, Map<String, Object>>

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/Gender.java
Required to fix a solicitor journey issue:
Was already done is CPS but was not ported over:
https://github.com/hmcts/div-case-progression-service/blob/master/src/main/java/uk/gov/hmcts/reform/divorce/transformservice/domain/model/ccd/Gender.java
=> Add notGiven to Gender enum

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/dn.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/dn.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java
=> Agree decree nisi

dependency-check-suppressions.xml, src/integrationTest/resources/application.properties
Reverting integration test URL to localhost
* Hardware:
* JDK:
=> Reverting integration tests reference to point to localhost

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategyUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json
=> Change ExistingPayment update logic to replace existing payments only

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategyUTest.java
=> Updated existing strategy to not mutate existingPayments

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java
=> Update existingPayments logic according to review

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/dn.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/dn.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/DnCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnCaseMapper.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/dn.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn.json
[DIV-3842](https://tools.hmcts.net/jira/browse/DIV-3842)
We have a new field in Decree Nisi where the user is able to upload additional documents. We do not have a corresponding mapping that stores the Document Store links of additional uploaded documents into CCD yet. This change adds that mapping.
Unit and integration test modifications. All tests pass.
=> Add DocumentsUploadedDN Mapping from Dn Session to CCD Data

dependency-check-suppressions.xml, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/reason-separation.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/reasonseparation.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/reason-separation.json
D8SeparationTimeTogetherPermitted, D8LivedTogetherMoreTimeThanPermitted are added as part of new separation dates change
Fixes # DIV-3660
* Hardware:
* JDK:
=> DIV-3660-New fields

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/payment/PaymentCollection.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategy.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/ExistingPaymentReferenceStrategyUTest.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json
=> Fix payment update code

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/dn.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/dn.json
renamed RespDefendsDivorce to RespWillDefendDivorce
Fixes #DIV-3840
=> DIV-3840 - renamed RespDefendsDivorce to RespWillDefendDivorce

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/config/HttpConnectionConfiguration.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/IdamApiHealthCheck.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/WebServiceHealthCheck.java, src/main/resources/application.yml, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/HealthCheckITest.java
Added 5s timeout on healthcheck
* Hardware:
* JDK:
=>  DIV-3885 Added timeout to healthcheck

build.gradle, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/CaseFormatterServiceApplication.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/insights/AppInsights.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/main/resources/application.yml, src/test/resources/fixtures/ccdtodivorcemapping/ccd/helpfeesnullcase.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/help-fees-null.json
- Bumped up java-logging to version 4.0.1
- Ignored empty elements on YesNo Answers
* Hardware:
* JDK:
=> [PREVIEW] Improve logging

Jenkinsfile_nightly, security.sh
=> set up divorce cfs security scan

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/d8-document.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/AmendPetitionToDivorceMapperUTest.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/amend-petition-case.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/amend-petition-divorce.json
Two new fields for CCD to divorce mapping 
Fixes # DIV-3742
Unit testing
=> DIV-3742 Added two new mapping fields for amend petition flow

build.gradle, dependency-check-suppressions.xml
Ticket: https://tools.hmcts.net/jira/browse/DIV-4018
Subtask 4: https://tools.hmcts.net/jira/browse/DIV-4022
Updated the owasp.dependencycheck task, a few dependencies in build.gradle and the dependency-check-suppressions.xml file
=> DIV-4018 suppressed dependencies update

build.gradle
=> fix-vulnerabilities

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToAosCaseMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/CoRespondentAnswersToCCDMapperTest.java, src/test/resources/fixtures/model/ccd/co-respondent/co-respondent-answers-no-cost.json, src/test/resources/fixtures/model/divorce/co-respondent/co-respondent-answers-no-cost.json
No map co-respondent cost if not available
* Hardware:
* JDK:
=> No map co-respondent cost if not available

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/RootController.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/controller/RootControllerTest.java
=> Added root controller and test

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/corespondent/AOS.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToAosCaseMapper.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/aos.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/test/resources/fixtures/model/ccd/co-respondent/co-respondent-answers.json, src/test/resources/fixtures/model/divorce/co-respondent/co-respondent-answers.json
Combined stories DIV-4446 and DIV-4447
DIV-4446
DIV-4447
* Hardware:
* JDK:
=>  DIV-4447  DIV-4446 Added receivedAOS field

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/usersession/DivorceSession.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/resources/fixtures/ccdtodivorcemapping/ccd/amend-petition-case.json, src/test/resources/fixtures/ccdtodivorcemapping/divorce/amend-petition-divorce.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/amend-petition-ccd-submitted.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/amend-petition-session-submit.json
When amending a case. this field (in the amended case) will hold the issueDate from the original case.
Unit tests.
=> DIV-4531: Adding mapping for previousIssueDate field

dependency-check-suppressions.xml
Supressing dependency check
spring-security-rsa-1.0.8.RELEASE.jar: ids:(cpe:/a:pivotal_software:spring_security:1.0.8, org.springframework.security:spring-security-rsa:1.0.8.RELEASE) : CVE-2018-1258
=> Supress dependency

build.gradle
=> Force upgrade of spring-security-crypto

src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/d8-document.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToCCDMapper.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/amend-petition-ccd-submitted.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/amend-petition-session-submit.json
[Amend Case: Family Man Reference - System should not allow to change FMR after Amend and issue the case in CCD](https://tools.hmcts.net/jira/browse/DIV-4672)
Ensure the front-end can submit the case reference.
=> DIV-4672 Ensure mapping of D8 Case Ref happens from divorce session to CCD for amend

Jenkinsfile_CNP, infrastructure/demo.tfvars, infrastructure/sandbox.tfvars, infrastructure/sprod.tfvars
Tactical Idam is deprecated, moving all to SIDAM
=> Point to SIDAM on all envs

build.gradle
Dependency analyse was failing, this fixes it by updating jacksonDatabind.
* Hardware:
* JDK:
=> Updated jacksonDatabind library

README.md
=> DIV-3264: Update readme

src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/AosCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToAosCaseMapper.java, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json
Move solicitor address field to AOS data
DIV-5545
* Hardware:
* JDK:
=> DIV-5545 Move solicitor field to AOS

build.gradle
CVE-2019-14379, CVE-2019-14439
=> fix failed security error

src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CoreCaseData.java, src/test/resources/fixtures/model/ccd/solicitorCaseDocumentsInput.json, src/test/resources/fixtures/model/ccd/solicitorCaseDocumentsOutput.json
https://tools.hmcts.net/jira/browse/DIV-4961
=> Added solicitorService method

web.config
To match https://github.com/hmcts/div-case-data-formatter/tree/master/lib
=> Fix incorrect appinsights version in web.config

Jenkinsfile_CNP, charts/div-cfs/Chart.yaml, charts/div-cfs/requirements.yaml
=> enableAksStagingDeployment() added to Jenkisfile_CNP

Jenkinsfile_CNP
AKS step was enabled for this pipeline, but the environment wasn't set.
- [ x ] Bug fix (non-breaking change which fixes an issue)
=> Setting up AAT as the environment for the functional tests

infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/variables.tf
=> Cleanup ASE

build.gradle, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/HealthCheckITest.java
- Updated Spring and all other outdated packages - serenity, Jackson, pitest etc. This addresses CVE-2020-5398
Unit and integration tests reran, ensured all failures are addressed
=> FIX-Address CVE-2020-5398 and upgrade dependencies

LICENSE.md, README.md, src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToCCDFormatTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/DivorceToDNCaseDataTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/IntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/divorce/ResourceLoader.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/domain/model/ccd/CollectionMember.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/DefaultHttpEntityFactory.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/CCDCaseToDivorceMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DivorceCaseToDnClarificationMapper.java, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/DocumentCollectionDivorceFormatMapper.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/HealthCheckITest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ObjectMapperTestUtil.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/ccdtodivorceformat/DocumentsMappingUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/DivorceCaseToDnClarificationMapperUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/mapper/divorcetoccdformat/DocumentCollectionCCDFormatMapperUTest.java, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/strategy/payment/PaymentContextUTest.java
- Updated ReadMe to be more clearer
- Updated license to 2020
- Reformatted to make code more readable
- Optimised imports
- Removed redundant "throws exception" from methods which don't throw exceptions
- Replaced deprecated "APPLICATION_JSON_UTF8_VALUE" with "APPLICATION_JSON_VALUE"
=> Updated readme and license. Code clean up etc

Jenkinsfile_CNP, build.gradle, dependency-check-suppressions.xml, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RPET-242
=> RPET-242: Remove deprecated method installCharts and client_id variable

build.gradle, infrastructure/main.tf
Add provider "azurerm" to fix failing pipeline.
=> Add provider

build.gradle
Bump up tomcat version CVE-2020-11996
* Hardware:
* JDK:
=> Update Tomcat version

Dockerfile, build.gradle, lombok.config
=> RPET-263 Upgrade to Java 11

README.md
=> Update README.md java reference

build.gradle
=> RPET-520: bump owasp dependency

build.gradle, dependency-check-suppressions.xml
upgrading tomcat to latest version and suppressing dependency failures for a month
jeremylong/DependencyCheck#2926
https://hmcts-reform.slack.com/archives/C8SR5CAMU/p1603811478231300
=> upgrading tomcat to latest version and suppressing failures 

build.gradle, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DIV-6180
Adding served by process service data to session data in common lib project
=> DIV-6180-Bumping-up-version-to-v1.2.1-for process-server-service

build.gradle, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/aos.json, src/test/resources/fixtures/divorcetoccdmapping/ccd/aos.json, src/test/resources/fixtures/divorcetoccdmapping/divorce/aos.json
Upgrading div-common-lib. To use new version of mapper
=> Upgrading div-common-lib to latest version

build.gradle, dependency-check-suppressions.xml, src/main/resources/application.yml
=> Fixing dependencies issues

build.gradle
This is a very quick fix, have bumped up the versions to fix the dependency and mutation test issues.
=> Bumped up the versions to fix dependency issues

dependency-check-suppressions.xml
This should be fixed by https://tools.hmcts.net/jira/browse/RPET-618
=> CVE-2020-25649 supression updated

build.gradle
Bumping up div-common-lib version
Fixes https://tools.hmcts.net/jira/browse/DIV-5463
=> Bumping up div-common-lib version

build.gradle, src/integrationTest/resources/fixtures/ccdtodivorcemapping/ccd/jurisdictionall.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/additional-payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/addresses.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/how-name-changed.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-6-12.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/jurisdiction-all.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/payment.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-adultery.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-desertion.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-separation.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/reason-unreasonable-behaviour.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/same-sex.json, src/integrationTest/resources/fixtures/ccdtodivorcemapping/divorce/service-application-documents.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/additionalpayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/addresscase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/d8document.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/hownamechanged.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdiction612.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/jurisdictionall.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/overwritepayment.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentcase.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/paymentidonly.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonadultery.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasondesertion.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonseparation.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/reasonunreasonablebehaviour.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/ccd/samesex.json, src/integrationTest/resources/fixtures/divorcetoccdmapping/divorce/jurisdiction-all.json
+ Bump div common lib to use new mapping
=> RPET-664: Brexit sol changes

build.gradle
bump common lib version
https://tools.hmcts.net/jira/browse/DIV-6872
=> bump comon lib version

charts/div-cfs/Chart.yaml
Upgrading to latest version of [chart-java (3.4.5)](https://github.com/hmcts/chart-java/releases/tag/v3.4.5)
https://tools.hmcts.net/jira/browse/RPET-921
platform operations upgrade
=> RPET-921 chart java bump

build.gradle
=> commonsIo             : '2.7'

README.md, build.gradle, src/test/java/uk/gov/hmcts/reform/divorce/caseformatterservice/config/CaseDataFormatterConfigurationTest.java
https://tools.hmcts.net/jira/browse/DFR-76
=> DFR 76 SpringBoot Update

build.gradle, charts/div-cfs/Chart.yaml
Migrate from bintray to jitpack for div common lib
DFR-517
- [ x] Bug fix (non-breaking change which fixes an issue)
=> DFR-517: Migrate from bintray to jitpack

build.gradle, charts/div-cfs/Chart.yaml
https://tools.hmcts.net/jira/browse/DFR-65
PR to test pipeline
=> Updated dependencies for tomcat, jacoco, serenity

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, dependency-check-suppressions.xml
Enable Fortify scan in nightly pipeline
DFR-464
- [x ] New feature (non-breaking change which adds functionality)
=> DFR-464: Fortify setup

build.gradle
Upgrade glassfish jakarta el
DFR-549
- [ x] Bug fix (non-breaking change which fixes an issue)
=> DFR-549: Upgrade glassfish jakarta el

build.gradle, charts/div-cfs/Chart.yaml, dependency-check-suppressions.xml
=> dependency check fix

dependency-check-suppressions.xml
=> Adding spring core suppressions

charts/div-cfs/Chart.yaml, charts/div-cfs/values.yaml
https://tools.hmcts.net/jira/browse/DTSSE-1395
=> Autoscaling div-cfs

dependency-check-suppressions.xml
=> dependency-suppression fix

build.gradle
=> nightly-dev: Updated snake.yaml version to 1.33

dependency-check-suppressions.xml
=> Supres jackson databind

build.gradle, dependency-check-suppressions.xml
=> Pipeline fixes

README.md, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-1712
=> DFR-1712 fix nightly

Dockerfile, Jenkinsfile_CNP, charts/div-cfs/Chart.yaml, dependency-check-suppressions.xml
[DTSSE-2994](https://tools.hmcts.net/jira/browse/DTSSE-2994)
=> Update Jenkinsfile_CNP allow old provider

infrastructure/state.tf
https://tools.hmcts.net/jira/browse/DTSSE-2994
=> Update azurerm to 3.X state.tf

dependency-check-suppressions.xml, src/main/java/uk/gov/hmcts/reform/divorce/caseformatterservice/management/monitoring/health/WebServiceHealthCheck.java
Update health check to log dependent service uri to help troubleshoot high health check count 
=> DFR-2642 Update health check to log dependent service uri

.github/renovate.json, dependency-check-suppressions.xml
https://tools.hmcts.net/jira/browse/DFR-3880
Disable renovate
=> DFR-3880: Disable renovate
